name: livepraise
base: core22
version: '0.0.9'
summary: Sistema de Projecao para igrejas
description: |
  Live Praise é um software dedicado a exibição de 
  Louvores, Biblias, Videos e outras atividades na igreja.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

parts:
  livepraise:
    plugin: nil
